# Generated by Django 3.2.12 on 2023-10-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_info', models.TextField(default='')),
                ('correct_answer', models.TextField(max_length=255)),
                ('incorrect_answer', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='covers/')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scenarios.levels')),
            ],
        ),
    ]
