# Generated by Django 4.2.5 on 2023-09-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_level', models.IntegerField()),
                ('scenario_title', models.CharField(max_length=255)),
                ('Background_info', models.TextField(max_length=255)),
                ('Decision_options', models.CharField(choices=[('Right', 'Right'), ('Wrong', 'Wrong')], max_length=255)),
                ('Reward_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scenarios.scenarios')),
            ],
        ),
    ]
