# Generated by Django 3.2.12 on 2023-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='correct_answer',
            field=models.TextField(default='The constitution permits all citizens to demonstrate or picket peacefully', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenarios',
            name='incorrect_answer',
            field=models.TextField(default="Any institution has the right to dictate what it's members say ", max_length=255),
            preserve_default=False,
        ),
    ]
