# Generated by Django 3.2.12 on 2023-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='level_title',
            field=models.CharField(max_length=256),
        ),
    ]
