# Generated by Django 4.2.5 on 2023-10-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='level_title',
            field=models.CharField(max_length=256),
        ),
    ]
