# Generated by Django 3.2.12 on 2023-10-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0002_auto_20230927_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarios',
            name='Decision_options',
        ),
    ]
