# Generated by Django 4.2.5 on 2023-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0002_alter_levels_level_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='image',
            field=models.URLField(max_length=2000),
        ),
    ]
