# Generated by Django 4.2.5 on 2023-10-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0003_remove_scenarios_decision_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='image',
            field=models.ImageField(default='images/badge_images/image-removebg-preview_16.png', upload_to='covers/'),
            preserve_default=False,
        ),
    ]
