# Generated by Django 4.2.5 on 2023-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Options', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=255)),
                ('Daily_Updates', models.TextField()),
                ('Category_Image', models.ImageField(upload_to='category_images/')),
                ('Is_Active', models.BooleanField()),
            ],
        ),
    ]
