# Generated by Django 4.2.5 on 2023-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Options',
            field=models.CharField(choices=[('Finance Bill', 'Finance Bill'), ('Bill of Rights', 'Bill of Rights')], max_length=255),
        ),
    ]
