# Generated by Django 4.2.5 on 2023-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
