# Generated by Django 4.2.5 on 2023-10-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='badge_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Options', models.CharField(choices=[('Finance Bill', 'Finance Bill'), ('Bill of Rights', 'Bill of Rights')], max_length=255)),
                ('Daily_Updates', models.TextField()),
                ('Category_Image', models.ImageField(upload_to='images/')),
                ('Is_Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_Image', models.ImageField(upload_to='covers/')),
                ('total_Scenarios', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_info', models.TextField()),
                ('correct_answer', models.TextField(max_length=255)),
                ('incorrect_answer', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='covers/')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.levels')),
            ],
        ),
    ]
