# Generated by Django 3.2.12 on 2023-09-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenario_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='badge_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Options', models.CharField(choices=[('Finance Bill', 'Finance Bill'), ('Bill of Rights', 'Bill of Rights')], max_length=255)),
                ('Daily_Updates', models.TextField()),
                ('Category_Image', models.ImageField(upload_to='images/')),
                ('Is_Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_Image', models.ImageField(upload_to='covers/')),
                ('total_Scenarios', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_level', models.IntegerField()),
                ('scenario_title', models.CharField(max_length=255, unique=True)),
                ('Background_info', models.TextField(max_length=255)),
                ('Decision_options', models.CharField(choices=[('Right', 'Right'), ('Wrong', 'Wrong')], max_length=255)),
                ('Reward_points', models.IntegerField()),
                ('scenario_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_scenarios', to='scenario_collection.scenariocollection')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scenarios')),
            ],
        ),
    ]
