# Generated by Django 3.2.12 on 2023-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Options', models.CharField(choices=[('Finance Bill', 'Finance Bill'), ('Bill of Rights', 'Bill of Rights')], max_length=255)),
                ('Daily_Updates', models.TextField()),
                ('Category_Image', models.ImageField(upload_to='images/')),
                ('Is_Active', models.BooleanField()),
            ],
        ),
    ]
