# Generated by Django 4.2.5 on 2023-09-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotmodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='bot_response',
            field=models.TextField(default='255', verbose_name='255'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
