# Generated by Django 4.2.5 on 2023-09-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotmodel', '0002_remove_message_message_message_bot_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bot_response',
            field=models.TextField(verbose_name='Response'),
        ),
    ]
