# Generated by Django 3.2.12 on 2023-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('User_Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='regularuser',
            name='custom_user',
        ),
        migrations.RemoveField(
            model_name='regularuser',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='regularuser',
            name='user_permissions_related',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='No available default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='No default available', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_users', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='RegularUser',
        ),
    ]
