# Generated by Django 3.2.12 on 2023-09-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Registration', '0002_auto_20230918_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
