# Generated by Django 3.2.12 on 2023-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Registration', '0003_auto_20230918_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
