# Generated by Django 4.2.5 on 2023-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_level', models.IntegerField()),
                ('scenario_title', models.CharField()),
                ('Background_info', models.TextField()),
                ('Decision_options', models.CharField()),
                ('Reward_points', models.IntegerField()),
            ],
        ),
    ]
