# Generated by Django 3.2.12 on 2023-09-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='Background_info',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='Decision_options',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='Reward_points',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='scenario_level',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='scenario_title',
            field=models.CharField(max_length=255),
        ),
    ]
