# Generated by Django 4.2.5 on 2023-09-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_collection', '0001_initial'),
        ('Scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarios',
            name='scenario_collection',
            field=models.ForeignKey(default='255', on_delete=django.db.models.deletion.CASCADE, to='scenario_collection.scenariocollection'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scenarios',
            name='scenario_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
