# Generated by Django 3.2.12 on 2023-09-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0002_auto_20230912_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='scenario_level',
            field=models.IntegerField(),
        ),
    ]
