# Generated by Django 4.2.5 on 2023-09-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_collection', '0001_initial'),
        ('Scenarios', '0002_scenarios_scenario_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='scenario_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='scenario_collection.scenariocollection'),
        ),
    ]
