# Generated by Django 3.2.12 on 2023-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0003_alter_scenarios_scenario_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='Reward_points',
            field=models.IntegerField(),
        ),
    ]
