# Generated by Django 3.2.12 on 2023-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0005_alter_scenarios_scenario_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='scenario_title',
            field=models.CharField(max_length=255),
        ),
    ]
