# Generated by Django 3.2.12 on 2023-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0006_alter_scenarios_scenario_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarios',
            name='Decision_options',
            field=models.CharField(choices=[('Right', 'Right'), ('Wrong', 'Wrong')], max_length=255),
        ),
    ]
