# Generated by Django 3.2.12 on 2023-09-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scenarios', '0007_alter_scenarios_decision_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scenarios.scenarios')),
            ],
        ),
    ]
