# Generated by Django 4.2.5 on 2023-09-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariocollection',
            name='total_Scenarios',
        ),
    ]
