# Generated by Django 4.2.5 on 2023-09-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_collection', '0002_remove_scenariocollection_total_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariocollection',
            name='total_Scenarios',
            field=models.IntegerField(default=0),
        ),
    ]
