# Generated by Django 3.2.12 on 2023-09-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Options', models.CharField(choices=[('Finance Bill', 'Finance Bill'), ('Bill of Rights', 'Bill of Rights')], max_length=255)),
                ('Daily_Updates', models.TextField()),
                ('Category_Image', models.ImageField(upload_to='images/')),
                ('Is_Active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VirtualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='scenariocollection',
            name='total_Scenarios',
            field=models.IntegerField(default=0),
        ),
    ]
