# Generated by Django 4.2.5 on 2023-09-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_virtualitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='badge_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_texts', models.TextField(unique=True)),
                ('image', models.ImageField(upload_to='badge_images/')),
                ('description_texts', models.TextField(max_length=255)),
                ('gamified_elements', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2')], max_length=255)),
            ],
        ),
    ]
